version: "3.9"

services:
  client:
    container_name: "client"
    build:
      context: .
      dockerfile: ./Dockerfile.client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3000:3000

  server:
    container_name: "server"
    build:
      context: .
      dockerfile: ./Dockerfile.server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: soso01
      POSTGRES_PASSWORD: 12341234
    volumes:
      - ./db/data:/var/lib/postgresql/data
