FROM node:latest
WORKDIR /usr/src/app

COPY ./server/package.json /usr/src/app
COPY ./server/yarn.lock /usr/src/app
RUN yarn install

COPY ./server /usr/src/app
RUN npx prisma generate

CMD ["yarn", "start:dev"]
